let currentCaseId=null, evidence=[];
const $=id=>document.getElementById(id);
function openModal(){$('modal').classList.add('show')};function closeModal(){$('modal').classList.remove('show')};function addEvidence(){if(!currentCaseId){alert('Create or load a case first.');return}openModal()}
function render(){
 $('evidenceCount').textContent=evidence.length; $('sourcesCount').textContent=new Set(evidence.map(x=>x.source).filter(Boolean)).size;
 const score=window.caseScore||null, level=window.caseLevel||'No case selected'; $('riskScore').textContent=score?score+'%':'—'; $('riskLabel').textContent=level; $('gaugeValue').textContent=score?score+'%':'—'; $('gaugeText').textContent=level; $('.gauge').style.setProperty('--risk',(score||0)+'%');
 const tl=$('timeline'); if(!evidence.length){tl.innerHTML='<div class="empty">No evidence yet.</div>'}else tl.innerHTML=evidence.map(e=>`<div class="event"><div class="eventTop"><h3>${esc(e.description)}</h3><time>${esc(e.timestamp||'No timestamp')}</time></div><p><span class="tag">${esc(e.evidence_type)}</span> &nbsp; ${esc(e.source||'Unknown source')}</p></div>`).join('');
}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadCase(id){const r=await fetch('/api/cases/'+id);const d=await r.json();if(d.error)return alert(d.error);currentCaseId=id;evidence=d.evidence;window.caseScore=d.case.risk;window.caseLevel=d.risk_level;$('reportBtn').disabled=false;$('quickReport').disabled=false;$('title').value=d.case.title;$('incident').value=d.case.incident_type;$('notes').value=d.case.notes||'';$('signals').innerHTML=d.signals.length?d.signals.map(s=>`<li>${esc(s)} detected</li>`).join(''):'<li>No high-signal keywords</li>';render()}
$('createBtn').onclick=async()=>{const payload={title:$('title').value,incident_type:$('incident').value,notes:$('notes').value,evidence:[]};const r=await fetch('/api/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)return alert(d.error);await loadCase(d.id)};
$('demoBtn').onclick=async()=>{const r=await fetch('/api/demo-case',{method:'POST'});const d=await r.json();if(d.id)await loadCase(d.id);else alert(d.error||'Unable to load demo')};
$('addBtn').onclick=addEvidence;
async function saveEvidence(){const item={evidence_type:$('etype').value,description:$('edesc').value,timestamp:$('etime').value,source:$('esource').value};if(!item.description.trim())return alert('Enter an evidence description.');evidence.push(item);const payload={title:$('title').value,incident_type:$('incident').value,notes:$('notes').value,evidence};/* create a replacement case to keep backend simple */const r=await fetch('/api/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)return alert(d.error);currentCaseId=d.id;window.caseScore=d.risk;window.caseLevel=d.risk_level;$('reportBtn').disabled=false;$('quickReport').disabled=false;$('signals').innerHTML=d.signals.length?d.signals.map(s=>`<li>${esc(s)} detected</li>`).join(''):'<li>No high-signal keywords</li>';closeModal();$('edesc').value='';$('etime').value='';$('esource').value='';render()}
async function report(){if(currentCaseId)window.location='/api/cases/'+currentCaseId+'/report'}$('reportBtn').onclick=report;$('quickReport').onclick=report;render();
